// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniAdventureDotNetWeb.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiniAdventureDotNetWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220928030507_AddPageToDatabase")]
    partial class AddPageToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiniAdventureDotNetWeb.Models.Page", b =>
                {
                    b.Property<string>("ActionCode")
                        .HasColumnType("text");

                    b.Property<string>("ActionA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActionC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segment1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segment2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segment3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segment4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Segment5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActionCode");

                    b.ToTable("Pages");
                });
#pragma warning restore 612, 618
        }
    }
}
